### ISSUE TITLE
how can i get a mi_band_auth_key?

### ISSUE THREAD

**Issue by ljjsimon** [wuhan005/mebeats#7]
hi

**Comment by wuhan005** [comment]
http://www.freemyband.com/

**Comment by LittleCjun** [comment]
https://app.mi.com/details?id=com.huami.watch.hmwatchmanager 
这个可以吗

**Comment by wuhan005** [comment]
> [app.mi.com/details?id=com.huami.watch.hmwatchmanager](https://app.mi.com/details?id=com.huami.watch.hmwatchmanager)
> 这个可以吗

这个不清楚，看这个应用的 BundleID 好像是小米官方的，应该不行吧（？
