### ISSUE TITLE
My macOS Bug Sur could not connect to MiBand3 all the time

### ISSUE THREAD

**Issue by tt1k** [wuhan005/mebeats#8]
The mebeats-client seems to stopped at [this line of code](https://github.com/wuhan005/mebeats/blob/master/miband/miband.go#L52).
iPhone's bluetooth could always discover and connect to band successfully, but mac couldn't.
Any way to fix this, thanks.

**Comment by wuhan005** [comment]
Your iPhone **must disconnect** to the Mi Band when your Mac is trying to connect it.

And you can add this line of code: 
```go
log.Trace("%s - %s", a.LocalName(), a.Addr().String())
```
to print out the device name and address for testing.

**Comment by tt1k** [comment]
Thank you for your reply!

I did disconnect the Mi Band from iPhone before. But thanks to the line of code you replied before, I found the correct value of <mi_band_addr>: "dae24ff6838840c7bbea8e40acf9616d", which used to be "E7:78:1D:CD:DC:36".

Now it's working on my [Github Profile](https://github.com/IcedOtaku)!
